version: "3.9"

# Adapted from https://github.com/heartexlabs/label-studio/blob/ea7c526e9983399eddebe3c8fee9abf3e3bc062c/docker-compose.yml

services:
  app:
    restart: $RESTART_POLICY
    image: heartexlabs/label-studio:latest
    ports:
      - "${LABEL_STUDIO_EXPOSE:-127.0.0.1:8080}:8080"
    depends_on:
      - db
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PORT=5432
      - POSTGRE_PASSWORD
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
    #      - LOG_LEVEL=DEBUG
    volumes:
      - app-storage:/label-studio/data:rw
    command: label-studio

  db:
    image: postgres:11.5
    hostname: db
    restart: $RESTART_POLICY
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-storage:/var/lib/postgresql/data

volumes:
  app-storage:
    name: ${COMPOSE_PROJECT_NAME:-label-studio}_app-storage
  db-storage:
    name: ${COMPOSE_PROJECT_NAME:-label-studio}_db-storage
